# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_thumb:

            # adjust the image quality to 75%
            quality: 100

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [1050, 500]}

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background: {position: center }


                # use and setup the "thumbnail" filter
                # thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    # size: [1300, 550]

                    # crop the input image, if required
                    # mode: outbound
        product:
            quality: 100

            filters:
                thumbnail: { size: [272, 320]}
