framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        # dsn: 'smtp://localhost:1025?encryption=null&auth_mode=null'
        # dsn: 'smtp://localhost:0.0.0.0:1025'
        # envelope:
        #     recipients: ['ghassenbelhadj@gmail.com']
